# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               '@mstred'
tagline:             'A Software Developer'
url:                 https://mstred.github.io
baseurl:             /
paginate:            1
paginate_path:       '/post/:num'

# About/contact
author:
  name:              Edson Samuel Jr
  url:               https://twitter.com/mstred

# Custom vars
version:             1.0.0
